config/routes.rb
Rails.application.routes.draw do

  resources :schoolposts
  resources :schoolphotos
  mount Ckeditor::Engine => '/ckeditor'
  resources :schools do
    get :search, :on => :collection
    # resources :posts
    member do
      get :showpost, :showmain, :showreview, :showphoto
    end
    resources :schoolreviews
    resources :schoolphotos
    resources :schoolposts
  end
  resources :schoolposts do
    resources :schoolpostcomments
  end
  resources :schoolpostcomments , only: [:index, :create]
  get '/schoolpostcomments/new/(:parent_id)', to: 'schoolpostcomments#new', as: :new_schoolpostcomment
  #
  resources :followers do
    member do
      get :userfollowschool, :userunfollowschool
    end
  end

  get '/pages/mypost', to: 'pages#mypost', as: :mypost_pages
  get '/pages/home', to: 'pages#home', as: :home_pages
  resources :schoolreviews
  resources :photocomments, only: [:index, :create]
  get '/photocomments/new/(:parent_id)', to: 'photocomments#new', as: :new_photocomment
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'users/:id', to: 'users#posts'
  resources :users
  #set the root to /posts
  #get "posts/new"
  #get "posts/index"
  #get "posts/show"
  devise_for :users, path: '/account',
  path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/schoolpost.rb
class Schoolpost < ApplicationRecord
  belongs_to :school
  belongs_to :user
  belongs_to :posttopic
  has_many :schoolpostcomments
  has_many :photocomments#, as: :commentable
end

app/controllers/schoolposts_controller.rb
class SchoolpostsController < ApplicationController
  before_action :set_schoolpost, only: [:show, :edit, :update, :destroy]
  layout "school",except: [:index, :new]

  # GET /schoolposts
  # GET /schoolposts.json
  def index
    @schoolposts = Schoolpost.all
  end

  # GET /schoolposts/1
  # GET /schoolposts/1.json
  def show
    #1st you retrieve the post thanks to params[:post_id]

  #school = School.find(params[:school_id])
  #2nd you retrieve the comment thanks to params[:id]

  #@schoolpost = school.schoolposts.find(params[:id])
  #@school = School.find(params[:school_id])
  #@schoolpost = @school.schoolposts.find(params[:id])
  @schoolpost = Schoolpost.find(params[:id])
  @school = @schoolpost.school
  @photocomments = @schoolpost.photocomments.hash_tree
  @schoolpostcomments = @schoolpost.schoolpostcomments.hash_tree
  @schoolpostcomment = Schoolpostcomment.new
    # @schoolcomment = Schoolcomment.new
    # @schoolcomments = @schoolpost.schoolcomments
  end

  # GET /schoolposts/new
  def new
    if params[:school_id]
      @school = School.find(params[:school_id])
      render layout: "school"
    else
      @schoolpost = Schoolpost.new
      @schoolfollow = @current_user.following_by_type('School')
      render layout: "application"
    end

  end

  # GET /schoolposts/1/edit
  def edit
  end

  # POST /schoolposts
  # POST /schoolposts.json
  def create
    if params[:school_id]
      @school = School.find(params[:school_id])
      @schoolpost = @school.schoolposts.new(schoolpost_params)
    else
      @schoolpost = Schoolpost.new(schoolpost_params)
    end
    if @schoolpost.save
      flash[:success] = "Success!"
      redirect_to controller: 'schools', action: 'showpost', id: params[:school_id].nil? ? schoolpost_params[:school_id] : params[:school_id]
    else
      flash[:error] = @schoolpost.errors.full_messages
      redirect_to new_school_schoolpost_path
    end

  end

  # PATCH/PUT /schoolposts/1
  # PATCH/PUT /schoolposts/1.json
  def update
    respond_to do |format|
      if @schoolpost.update(schoolpost_params)
        format.html { redirect_to @schoolpost, notice: 'Schoolpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @schoolpost }
      else
        format.html { render :edit }
        format.json { render json: @schoolpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schoolposts/1
  # DELETE /schoolposts/1.json
  def destroy
    @schoolpost.destroy
    respond_to do |format|
      format.html { redirect_to schoolposts_url, notice: 'Schoolpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schoolpost
      @schoolpost = Schoolpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schoolpost_params
      params.require(:schoolpost).permit(:view, :title, :content, :posttopic_id, :user_id, :school_id)
    end
end

app/helpers/schoolposts_helper.rb
module SchoolpostsHelper
  def grouped_communities_options_for_select(selected_conversation_id = nill,communities)
    options = []
    # communities.all.map do |c|
    #     options.push([c.communitytype, [c.id, c.name]])
    # end

    community_by_type = communities.all.group_by(&:communitytype)

    community_by_type.each do |communitytype, communities|
      options1 = []
      communities.each do |community|
        options1.push([community.cnname, community.id])
      end
      options.push([communitytype,options1])
    end


    grouped_options_for_select(options)
    #render(options)
  end
end

app/views/schoolposts/_form.html.erb
<%= form_with(model: [ @school, @school.schoolposts.build ], local: true) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content %>
  </div>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit class: "btn buttoncolor btn-sm active" %>
  </div>
<% end %>
1111

app/views/schoolposts/_form1.html.erb
<%= form_with(model: @schoolpost, local: true) do |form| %>

  <div class="field">
    <%= form.label :标题 %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :选择区域（只有关注社区才可以发帖哦） %>
    <%= form.select :school_id, grouped_communities_options_for_select(1,@schoolfollow),{}, {class: "form-control"} %>
  </div>
  <div class="field">
    <%= form.label :选择话题 %>
    <%= form.collection_select :posttopic_id, Posttopic.all, :id, :topicname,{},{class: "form-control"} %>
  </div>
  <div class="field">
    <%= form.label :正文 %>
    <%= form.cktext_area :content %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit class: "btn buttoncolor btn-sm active" %>
  </div>
  <% grouped_communities_options_for_select(1,@schoolfollow) %>

<% end %>

app/views/schoolposts/edit.html.erb
<h1>Editing Schoolpost</h1>

<%= render 'form', schoolpost: @schoolpost %>

<%= link_to 'Show', @schoolpost %> |
<%= link_to 'Back', schoolposts_path %>

app/views/schoolposts/index.html.erb
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>View</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schoolposts.each do |schoolpost| %>
      <tr>
        <td><%= schoolpost.view %></td>
        <td><%= schoolpost.title %></td>
        <td><%= schoolpost.text %></td>
        <td><%= link_to 'Show', schoolpost %></td>
        <td><%= link_to 'Edit', edit_schoolpost_path(schoolpost) %></td>
        <td><%= link_to 'Destroy', schoolpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schoolpost', new_schoolpost_path %>

app/views/schoolposts/new.html.erb
<div class="mx-3 my-3">
<h4>发表新帖子</h4>

<% if @school %>
<%= render 'form', schoolpost: @schoolpost %>
<% else %>
<%= render 'form1', schoolpost: @schoolpost %>
<% end %>


<% if @school %>
<%= link_to 'Back', showpost_school_path(@school) %>
<% end %>
</div>

app/views/schoolposts/show.html.erb
<p id="notice"><%= notice %></p>

<h5 class="card-title">
  <%= @schoolpost.title %>
</h5>

<p>
  <%= @schoolpost.content.html_safe %>
</p>


<%= form_with(model: [ @schoolpost, @schoolpost.schoolpostcomments.build ], local: true) do |form| %>
  <div class="field">
    <%= form.text_area :content, class: 'form-control', placeholder: "输入评论" %>
  </div>

  <div class="actions">
    <%= form.submit '评论', class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

<%= schoolpostcomments_tree_for @schoolpostcomments %>