config/routes.rb
Rails.application.routes.draw do

  resources :schoolposts
  resources :schoolphotos
  mount Ckeditor::Engine => '/ckeditor'
  resources :schools do
    get :search, :on => :collection
    # resources :posts
    member do
      get :showpost, :showmain, :showreview, :showphoto
    end
    resources :schoolreviews
    resources :schoolphotos
    resources :schoolposts
  end
  resources :schoolposts do
    resources :schoolpostcomments
  end
  resources :schoolpostcomments , only: [:index, :create]
  get '/schoolpostcomments/new/(:parent_id)', to: 'schoolpostcomments#new', as: :new_schoolpostcomment
  #
  resources :followers do
    member do
      get :userfollowschool, :userunfollowschool
    end
  end

  get '/pages/mypost', to: 'pages#mypost', as: :mypost_pages
  get '/pages/home', to: 'pages#home', as: :home_pages
  resources :schoolreviews
  resources :photocomments, only: [:index, :create]
  get '/photocomments/new/(:parent_id)', to: 'photocomments#new', as: :new_photocomment
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'users/:id', to: 'users#posts'
  resources :users
  #set the root to /posts
  #get "posts/new"
  #get "posts/index"
  #get "posts/show"
  devise_for :users, path: '/account',
  path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/photocomment.rb
class Photocomment < ApplicationRecord
  belongs_to :schoolpost
  belongs_to :user
  has_closure_tree
end

app/controllers/photocomments_controller.rb
class PhotocommentsController < ApplicationController
  before_action :set_photocomment, only: [:show, :edit, :update, :destroy]

  # GET /photocomments
  # GET /photocomments.json
  def index
    @photocomments = Photocomment.hash_tree
  end

  # GET /photocomments/1
  # GET /photocomments/1.json
  def show
  end

  # GET /photocomments/new
  def new
    @photocomment = Photocomment.new(parent_id: params[:parent_id])
  end

  # GET /photocomments/1/edit
  def edit
  end

  # POST /photocomments
  # POST /photocomments.json
  def create

    if params[:photocomment][:parent_id].present?
        parent = Photocomment.find_by_id(params[:photocomment].delete(:parent_id))
        @photocomment = parent.children.build(photocomment_params)
      else
        @photocomment = Photocomment.new(photocomment_params)
      end

      if @photocomment.save
        flash[:success] = 'Your comment was successfully added!'
        redirect_to root_url
      else
        render 'new'
      end

  end

  # PATCH/PUT /photocomments/1
  # PATCH/PUT /photocomments/1.json
  def update
    respond_to do |format|
      if @photocomment.update(photocomment_params)
        format.html { redirect_to @photocomment, notice: 'Photocomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @photocomment }
      else
        format.html { render :edit }
        format.json { render json: @photocomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photocomments/1
  # DELETE /photocomments/1.json
  def destroy
    @photocomment.destroy
    respond_to do |format|
      format.html { redirect_to photocomments_url, notice: 'Photocomment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photocomment
      @photocomment = Photocomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photocomment_params
      params.require(:photocomment).permit(:content,:parent_id)
    end
end

app/helpers/photocomments_helper.rb
module PhotocommentsHelper
  def photocomments_tree_for(photocomments)
  photocomments.map do |photocomment, nested_photocomments|
    render(photocomment) +
        (nested_photocomments.size > 0 ? content_tag(:div, photocomments_tree_for(nested_photocomments), class: "replies") : nil)
  end.join.html_safe
end
end

app/views/photocomments/_form.html.erb
<%= form_with(model: photocomment, local: true) do |form| %>
  <% if photocomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photocomment.errors.count, "error") %> prohibited this photocomment from being saved:</h2>

      <ul>
      <% photocomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
    <%= form.hidden_field :parent_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photocomments/_photocomment.html.erb
<div class="well">
  <blockquote>
    <p><%= photocomment.content %></p>
  </blockquote>

  <p><%= link_to 'reply', new_photocomment_path(photocomment.id) %></p>
</div>

app/views/photocomments/edit.html.erb
<h1>Editing Photocomment</h1>

<%= render 'form', photocomment: @photocomment %>

<%= link_to 'Show', @photocomment %> |
<%= link_to 'Back', photocomments_path %>

app/views/photocomments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photocomments</h1>



<br>

<%= link_to 'New Photocomment', new_photocomment_path %>


<%= photocomments_tree_for @photocomments %>

app/views/photocomments/new.html.erb
<h1>New Photocomment</h1>

<% if @photocomment.parent %>
  <%= render 'photocomment', photocomment: @photocomment.parent, from_reply_form: true %>
<% end %>

<%= render 'form', photocomment: @photocomment %>

<%= link_to 'Back', photocomments_path %>

app/views/photocomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @photocomment.content %>
</p>

<%= link_to 'Edit', edit_photocomment_path(@photocomment) %> |
<%= link_to 'Back', photocomments_path %>