config/routes.rb
Rails.application.routes.draw do

  resources :schoolposts
  resources :schoolphotos
  mount Ckeditor::Engine => '/ckeditor'
  resources :schools do
    get :search, :on => :collection
    # resources :posts
    member do
      get :showpost, :showmain, :showreview, :showphoto
    end
    resources :schoolreviews
    resources :schoolphotos
    resources :schoolposts
  end
  resources :schoolposts do
    resources :schoolpostcomments
  end
  resources :schoolpostcomments , only: [:index, :create]
  get '/schoolpostcomments/new/(:parent_id)', to: 'schoolpostcomments#new', as: :new_schoolpostcomment
  #
  resources :followers do
    member do
      get :userfollowschool, :userunfollowschool
    end
  end

  get '/pages/mypost', to: 'pages#mypost', as: :mypost_pages
  get '/pages/home', to: 'pages#home', as: :home_pages
  resources :schoolreviews
  resources :photocomments, only: [:index, :create]
  get '/photocomments/new/(:parent_id)', to: 'photocomments#new', as: :new_photocomment
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'users/:id', to: 'users#posts'
  resources :users
  #set the root to /posts
  #get "posts/new"
  #get "posts/index"
  #get "posts/show"
  devise_for :users, path: '/account',
  path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/school.rb
class School < ApplicationRecord
  has_many :schoolposts
  has_many :schoolreviews
  has_many :schoolphotos
  mount_uploader :schoolimage, SchoolimageUploader
  #关注
  acts_as_followable

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  layout "school",except: [:index, :new]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  def search
    respond_to do |format|
      format.html
      format.json { @schools = School.where('LOWER(name) LIKE :term', term: "%#{params[:term].downcase}%")}
    end
  end
  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])
  end

  def showpost
    @school = School.find(params[:id])
  end

  def showmain
    @school = School.find(params[:id])
  end

  def showreview
    @school = School.find(params[:id])
  end

  def showphoto
    @school = School.find(params[:id])
  end
  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    @school = School.find(params[:id])
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      #@school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name,:cnname, :schoolintro, :image, :schoolimage)
    end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :学校英文 %>
    <%= form.text_field :name, :class => "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :学校中文 %>
    <%= form.text_field :cnname, :class => "form-control" %>
  </div>

  <!-- <div class="form-group">
      <%= form.label :学校徽章 %>
      <%= form.file_field :schoolimage %>
  </div> -->

  <div class="form-group">
    <%= form.label :学校介绍 %>
    <%= form.cktext_area :schoolintro%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn buttoncolor btn-sm active" %>
  </div>
<% end %>

app/views/schools/_schoolname.html.erb
<div class="schoolname">
<p>
  <% if false %>
  <% if @school.image.attached? %>
  <%= image_tag @school.image, class:"schoollogo", alt:"logo"%>
  <% end %>
  <% end %>
  <% if @school.schoolimage? %>
<%= image_tag @school.schoolimage.url , class:"schoollogo", alt:"logo"%>
<% end %>
  <%= @school.cnname %>
  <%= @school.name %>
  <%= link_to(userunfollowschool_follower_path(id: @school.id, format: 'js'), remote: true, id: "followschool-"+@school.id.to_s) do %>
  <button type="button" class="btn btn-outline-success btn-sm">
      取消关注
  </button>
  <% end %>
</p>
</div>

app/views/schools/edit.html.erb
<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<h1>学校管理</h1>
<%= link_to '新建学校', new_school_path, class: "btn buttoncolor btn-sm active"%>
<table>
<tr>
  <th>英文名</th>
  <th>中文名</th>
  <th colspan="3"></th>
<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.cnname %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/schools/new.html.erb
<div class="container">

<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>
<div>

app/views/schools/search.html.erb
<article class="app-cont">


  <section class="app-content">
    <div class="books-search">
      <input type="text" id="books-search-txt" autofocus>
      <div class="results" id="books-search-results"></div>
    </div>
  </section>

</article>

<% content_for :javascript do %>
  <script type='text/javascript'>
new app.Books;

   </script>
<% end %>

app/views/schools/show.html.erb
<p class="">
  <% if @school.schoolintro%>
  <%= @school.schoolintro.html_safe  %>
  <% else %>
  添加内容
  <% end %>
</p>
<div class="float-right">
<%= link_to image_tag("modify-black.png",class:"modifylogo"), {controller: 'schools', action: 'edit'}%>
</div><br>
<div>

app/views/schools/showmain.html.erb
<div class="discover-controls-wrapper"><div class="content-controls"><div class="types-tabs"> <a href="/explore/trending" class="content-control active" style="width: 72px;" data-text="Trending" data-content-type="trending">  Trending </a>  <a href="/explore/staff-picks" class="content-control " style="width: 88px;" data-text="Staff picks" data-content-type="staff-picks">  Staff picks </a>  <a href="/explore/text" class="content-control " style="width: 44px;" data-text="Text" data-content-type="text">  Text </a>  <a href="/explore/photos" class="content-control " style="width: 64px;" data-text="Photos" data-content-type="photos">  Photos </a>  <a href="/explore/gifs" class="content-control " style="width: 48px;" data-text="GIFs" data-content-type="gifs">  GIFs </a>  <a href="/explore/quotes" class="content-control " style="width: 65px;" data-text="Quotes" data-content-type="quotes">  Quotes </a>  <a href="/explore/links" class="content-control " style="width: 53px;" data-text="Links" data-content-type="links">  Links </a>  <a href="/explore/chats" class="content-control " style="width: 56px;" data-text="Chats" data-content-type="chats">  Chats </a>  <a href="/explore/audio" class="content-control " style="width: 56px;" data-text="Audio" data-content-type="audio">  Audio </a>  <a href="/explore/video" class="content-control " style="width: 54px;" data-text="Video" data-content-type="video">  Video </a>  <a href="/explore/asks" class="content-control " style="width: 50px;" data-text="Asks" data-content-type="asks">  Asks </a>  <span class="content-control more-controls hidden"><span class="type-text">More</span><i class="icon_arrow_carrot_down"></i></span></div></div></div>

<p>
  <strong>Text:</strong>
  <%= @school.name %>
</p>
<h2>Comments</h2>
<% @school.posts.each do |post| %>
  <p>
    <strong>Commenter:</strong>
    <%= post.description %>
  </p>


<% end %>

app/views/schools/showphoto.html.erb
<div id="lightgallery" class="schoolphoto">
  <% @school.schoolphotos.each do |schoolphoto| %>
    <%= schoolphoto.view %>
    <% if schoolphoto.photo? %>
  <a href=" <%= image_path schoolphoto.photo.url %>">
    <div style="background-image: url(
       <%= image_path schoolphoto.photo.url %>
     );" class="uiMediaThumbImg"></div>
  </a>
  <% end %>
  <% end %>
</div>
<div class="clear">
<h2>Add a comment:</h2>
</div>
<div>
<%= form_with(model: [ @school, @school.schoolphotos.build ], local: true) do |form| %>
  <p>
    <div class="form-group">
        <%= form.label :图片 %>
        <%= form.file_field :photo %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>

  	<br>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/schools/showpost.html.erb
  <%= link_to(new_school_schoolpost_path(@school)) do %>
  <button type="button" class="btn btn-secondary">
      写文章
      </button>
  <% end %>

<% @school.schoolposts.each do |schoolpost| %>
<div class="card bg-light mt-3">
  <!-- <div class="card-header">
    <%= schoolpost.user.nickname %>
  </div> -->
  <div class="card-body">
    <div class="mb-3 author">
      <h7>
        <%= schoolpost.user.nickname %>
      </h7>
    </div>
    <h5 class="card-title">
      <%= link_to(school_schoolpost_path(@school, schoolpost)) do %>
          <%= schoolpost.title %>
      <% end %></h5>
    <p class="card-text">
      <span class="postpreview">
        <%= truncate(Sanitize.fragment( schoolpost.content), length:100) %>
        <%= link_to(school_schoolpost_path(@school, schoolpost)) do %>
            阅读全文
        <% end %>
      </span>
    </p>
    <!-- <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer> -->
    <ul class="list-inline text-muted mt-2">
      <li class="list-inline-item">
        <span>2 days, 8 hours </span>
      </li>
      <li class="list-inline-item">|</li>
      <li class="list-inline-item">
        <span class="">2个评论</span>
      </li>
    </ul>
  </div>
  <!-- <div class="card-footer text-muted">
  2 days ago
</div> -->
</div>
<% end %>

<!--

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div> -->

app/views/schools/showreview.html.erb
<p>
  <strong>Text:</strong>
  <%= @school.name %>
</p>
<h2>Comments</h2>
<% @school.schoolreviews.each do |schoolreview| %>
  <p>
    <%= schoolreview.user.nickname %> <strong> 评论:</strong>
    <%= schoolreview.comment %>
  </p>

<% end %>

<h2>Add a comment:</h2>

<%= form_with(model: [ @school, @school.schoolreviews.build ], local: true) do |form| %>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_field :comment %>
    <%= form.hidden_field :user_id, value: current_user.id %>

  	<br>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>