config/routes.rb
Rails.application.routes.draw do

  resources :schoolposts
  resources :schoolphotos
  mount Ckeditor::Engine => '/ckeditor'
  resources :schools do
    get :search, :on => :collection
    # resources :posts
    member do
      get :showpost, :showmain, :showreview, :showphoto
    end
    resources :schoolreviews
    resources :schoolphotos
    resources :schoolposts
  end
  resources :schoolposts do
    resources :schoolpostcomments
  end
  resources :schoolpostcomments , only: [:index, :create]
  get '/schoolpostcomments/new/(:parent_id)', to: 'schoolpostcomments#new', as: :new_schoolpostcomment
  #
  resources :followers do
    member do
      get :userfollowschool, :userunfollowschool
    end
  end

  get '/pages/mypost', to: 'pages#mypost', as: :mypost_pages
  get '/pages/home', to: 'pages#home', as: :home_pages
  resources :schoolreviews
  resources :photocomments, only: [:index, :create]
  get '/photocomments/new/(:parent_id)', to: 'photocomments#new', as: :new_photocomment
  root 'pages#home'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  #get 'users/:id', to: 'users#posts'
  resources :users
  #set the root to /posts
  #get "posts/new"
  #get "posts/index"
  #get "posts/show"
  devise_for :users, path: '/account',
  path_names: { sign_in: 'login', sign_out: 'logout'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale
  before_action :set_timezone, if: :user_signed_in?
  layout :layout_by_resource

  def set_locale
    I18n.locale = extract_locale_from_user ||
                  params[:locale] ||
                  extract_locale_from_subdomain ||
                  extract_locale_from_tld || I18n.default_locale
  end

  def extract_locale_from_user
    current_user.language if current_user
  end

  def extract_locale_from_tld
    parsed_locale = request.host.split('.').last
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def extract_locale_from_subdomain
    parsed_locale = request.subdomains.first
    I18n.available_locales.map(&:to_s).include?(parsed_locale) ? parsed_locale : nil
  end

  def default_url_options
    #链接添加local
    #{ locale: I18n.locale }
    { locale: nil }
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:language, :timezone, :nickname])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: [:language, :timezone, :nickname])
  end

  def set_timezone
    unless current_user.timezone.empty?
      Time.zone = current_user.timezone
    end
  end

  private

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def available_locales
    hidden = [:zh] # These are base locales we don't want to show
    (I18n.available_locales - hidden)
  end

  def locale_name_pairs
    available_locales.map do |locale|
      [I18n.t(:language, :locale => locale.to_s).to_s, locale.to_s]
    end
  end

  def create_links
    html=""
    locale_name_pairs.each do |link|
      html += content_tag(:li, link_to("#{link.first}", url_for(request.params.merge(:locale => link.last))))
    end
    html.html_safe
  end

  def code2language(code)
    I18n.t(:language, :locale => code)
  end

  def title
    if content_for?(:title)
      I18n.t('appname') + ' | ' + content_for(:title)
    elsif "#{ controller_path.tr('/', '.') }".include?('devise') || ['create','update'].any? {|e| action_name.include? e}
      I18n.t('appname')
    else
      I18n.t('appname') + ' | ' + I18n.t("#{ controller_path.tr('/', '.') }.#{ action_name }.title", default: :site_name)
    end
  end

  def flash_class(level)
    case level
    when :notice then "alert alert-info alert-dismissible fade show"
    when :success then "alert alert-success alert-dismissible fade show"
    when :error then "alert alert-danger alert-dismissible fade show"
    when :alert then "alert alert-warning alert-dismissible fade show"
    end
  end

  def current_action?(controller: 'default', action: 'default')
      (controller == params[:controller]) and (action == params[:action])
  end

  def active_class(link_path)
    current_page?(link_path) ? 'active1s' : ""
  end

end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light navstyle">
  <div>
  <%= link_to(root_path, class: "navbar-brand icon  mr-0 mr-md-2") do %>
      H海草
  <% end %>
  <form class ="form-inline-1">
    <div class="form-group" style="display:inline;">
      <div class="schools-search">
        <input class="searchinput" id="schools-search-txt" name="a" type="text" placeholder="搜索学校，地区，专业">
        <button class="searchbtn" type="submit"><i class="fa fa-search"></i></button>
        <div class="results" id="schools-search-results"></div>
      </div>
    </div>
  </form>
</div>


<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav ml-md-auto">
    <% if user_signed_in? %>
        <li class="nav-item dropdown mx-3">
              <a class="nav-link" href="#" id="navbarDropdown"
                 role="button" data-toggle="dropdown" aria-haspopup="true"
                 aria-expanded="false">
                 <%= fa_icon "user 2x" %>

              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to(edit_user_registration_path,
                  class: 'dropdown-item') do %>
                  <%= fa_icon "cog 2x" %>
                更改账号
                <% end %>
            <div class="dropdown-divider"></div>
                <%= link_to(destroy_user_session_path, method: :delete, confirm: "Are you sure?", class: "dropdown-item") do %>
                <%= fa_icon "sign-out 2x" %>
                    登出
                <% end %>
              </div>
        </li>
        <li class="nav-item mr-3">
          <%= link_to(new_schoolpost_path, {class: "nav-link" }) do %>
          <%= fa_icon "plus-square 2x" %>
          <% end %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to(new_schoolpost_path, {class: "nav-link" }) do %>
          <%= fa_icon "bell 2x" %>
          <% end %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to(new_schoolpost_path, {class: "nav-link" }) do %>
          <%= fa_icon "th 2x" %>
          <% end %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to(new_schoolpost_path, {class: "nav-link" }) do %>
          <%= fa_icon "envelope 2x" %>
          <% end %>
        </li>
    <% else %>
        <li class="nav-item mr-3">
            <%= link_to(new_user_session_path, class: "nav-link") do %>
                <%= fa_icon "sign-in 2x" %>
                <%= t('devise.sessions.new.sign_in')%>
            <% end %>
        </li>
    <% end %>

  </ul>

</div>

</nav>

app/views/application/_headerl2.html.erb
<nav class="navbar-expand-md navbar-dark">
  <div class="types-tabs">
    <%= link_to("推荐", home_pages_path,  class: current_action?(controller: 'pages', action: 'home')? 'active1': '') %>
    <% if user_signed_in? %>
      <%= link_to("关注", mypost_pages_path,  class: current_action?(controller: 'pages', action: 'mypost')? 'active1': '') %>
    <% end %>
    <a>
      附近
    </a>
     <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= fa_icon "filter 1x" %></a>
     <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
       <div class="dropdown-divider"></div>
       <% if current_action?(controller: 'pages', action: 'home') %>
          <%= link_to("显示全部", home_pages_path, class: "dropdown-item filterdrop") %>
       <% end %>
       <% if current_action?(controller: 'pages', action: 'mypost') %>
          <%= link_to("显示全部", mypost_pages_path, class: "dropdown-item filterdrop") %>
       <% end %>
       <% @posttopics.each do |posttopic| %>
             <div class="dropdown-divider"></div>
             <% if current_action?(controller: 'pages', action: 'home') %>
               <%= link_to(home_pages_path(posttype: posttopic.id),  class: "dropdown-item filterdrop")  do %>
                    <%= posttopic.topicname %>
               <% end %>
             <% end %>
             <% if current_action?(controller: 'pages', action: 'mypost') %>
               <%= link_to(mypost_pages_path(posttype: posttopic.id),  class: "dropdown-item filterdrop")  do %>
                    <%= posttopic.topicname %>
               <% end %>
             <% end %>
       <% end %>
       <div class="dropdown-divider"></div>
    </div>

</nav>

app/views/application/_notifications.html.erb
<% unless flash.empty? %>
<% flash.each do |key, value| %>
    <div class="<%= flash_class(key.to_sym) %>" role="alert">
	<%= value%>
	<button type="button" class="close" data-dismiss="alert"
		aria-label="Close">
	    <span aria-hidden="true">&times;</span>
	</button>
    </div>
<% end %>
<% end %>

<script type="text/javascript">
    <% flash.each do |f| %>
	    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	    toastr['<%= type %>']('<%= f[1] %>');
   <% end %>
</script>

app/views/application/_schoolheaderl2.html.erb
<nav class="navbar-expand-md navbar-dark">
  <div class="types-tabs">
    <%= link_to("主页", school_path(@school),  class: current_action?(controller: 'schools', action: 'show')? 'active1': '') %>
    <%= link_to("点评", showreview_school_path(@school),  class: current_action?(controller: 'schools', action: 'showreview')? 'active1': '') %>
    <%= link_to("照片", showphoto_school_path(@school),  class: current_action?(controller: 'schools', action: 'showphoto')? 'active1': '') %>
    <%= link_to("帖子", showpost_school_path(@school),  class:         if current_action?(controller: 'schoolposts', action: 'show') || current_action?(controller: 'schools', action: 'showpost') ||
    current_action?(controller: 'schoolposts', action: 'new')
           'active1' else '' end) %>
    <a>
      活动
    </a>
    <a>
      视频
    </a>
    <a>
      社群
    </a>
    <a>
      校友
    </a>
    <a>
      交流
    </a>
    <a>
      话题
    </a>
    <a>
      讨论
    </a>
    <a>
      工作
    </a>
  </div>
</nav>